// Find data at https://esprit.magister.net/api/personen/69726/aanmeldingen/136419/cijfers/cijferoverzichtvooraanmelding
// TODO: add handelingsdelen
// TODO: add SE's
export default {
    type: 'DIPLOMA',
    fullname: 'diplomacijfer',
    shortname: 'diploma',
    id: 'rbfj8raw3r',
    grades: [
        {
            type: 'VAK',
            fullname: 'Natuurkunde',
            shortname: 'Na.',
            id: 'oeh1gxsud0',
            se_assignments: [
                {
                    type: 'PO',
                    year: 5,
                    period: 1,
                    description:
                        'Engelstalige presentatie in groepsverband over een aan klimaatverandering en duurzaamheid gerelateerd mondiaal probleem',
                    domains: ['A', 'G2'],
                    weight: 16,
                    magister: 'NAT8202',
                    id: '0otgmtlnnu',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 2,
                    description:
                        'Toets over periodieke verschijnselen, biofysica, materiaaleigenschappen en medische beeldvorming',
                    domains: ['A', 'B1', 'B2', 'E1', 'G1'],
                    weight: 34,
                    magister: 'NAT8203',
                    id: 'ia3n5mpq8h',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 3,
                    description:
                        'Technisch ontwerp van een robot opstellen in groepsverband',
                    domains: ['A', 'I3'],
                    weight: 16,
                    magister: 'NAT8204',
                    id: 'gk6bpztd3m',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 3,
                    description:
                        'Individueel portfolio van verslaglegging van experimenten op het gebied van periodieke verschijnselen en elektromagnetisme.',
                    domains: ['A', 'I1'],
                    weight: 17,
                    magister: 'NAT8205',
                    id: 'vktv19mfe2',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 4,
                    description:
                        'Modelstudie over een bewegingsverschijnsel\nIndividueel werk',
                    domains: ['A', 'I2'],
                    weight: 17,
                    magister: 'NAT8208',
                    id: 'p9zxizlb5a',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/wiskunde-b-vwo-2',
                    id: 'lo5r266gs9',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Scheikunde',
            shortname: 'Sck.',
            id: 'n5x8d27vgf',
            se_assignments: [
                {
                    type: 'PO',
                    year: 5,
                    period: 1,
                    description:
                        'Engelstalige presentatie in groepsverband over een door klimaatverandering veroorzaakt mondiaal probleem',
                    domains: ['A', 'C9', 'E3', 'F4', 'G4'],
                    weight: 15,
                    magister: 'SCHK8201',
                    id: 'bibthnx1dj',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 2,
                    description:
                        'Schriftelijk examen over de chemie van voeding en gezondheid',
                    domains: ['A', 'B1', 'C1', 'C2', 'C5', 'C7'],
                    weight: 30,
                    magister: 'SCHK8202',
                    id: 'gbx6hdqihp',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 3,
                    description:
                        'Individuele opdracht naar aanleiding van een bezoek aan externe organisatie op het gebied van duurzaamheid',
                    domains: ['A', 'C8', 'F5', 'G5'],
                    weight: 20,
                    magister: 'SCHK8204',
                    id: '1zdnkkmoho',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 4,
                    description:
                        'Individuele verslaglegging van uitvoer van en werkhouding voor verscheidene practica op het gebied van gezondheid',
                    domains: ['A', 'C10', 'D2', 'D4', 'C5'],
                    weight: 20,
                    magister: 'SCHK8203',
                    id: 'z01wr9t5g8',
                },
                {
                    type: 'PO',
                    year: 6,
                    period: 2,
                    description:
                        'Onderzoeks- of ontwerpopdracht formuleren over een nieuwe chemische toepassing in de bestaande markt, deze uitvoeren en daar een verslag van doen.',
                    domains: ['A', 'E4', 'E5'],
                    weight: 15,
                    id: 'dmrb2mirx2',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/scheikunde-vwo-2',
                    id: 'gwhgd1zvbn',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Biologie',
            shortname: 'Bio.',
            id: 'q8uicp9j8r',
            se_assignments: [
                {
                    type: 'PO',
                    year: 5,
                    period: 1,
                    description:
                        'Engelstalige presentatie in groepsverband over een aan klimaatverandering gerelateerd mondiaal probleem',
                    domains: ['A', 'C3', 'F3'],
                    weight: 20,
                    magister: 'BIOL8201',
                    id: 'd4vz6v5b99',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 1,
                    description:
                        'Geschreven product(en) dat inzicht geeft op het gebied van seksualiteit en gedrag\nIndividueel werk',
                    domains: ['A', 'D3', 'D4'],
                    weight: 20,
                    magister: 'BIOL8202',
                    id: 'x4mnsu5pms',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 2,
                    description:
                        'Schriftelijke toets over de werking van het menselijk lichaam op gebied van voeding en gezondheid',
                    domains: ['A', 'B5', 'B6', 'B7', 'C2'],
                    weight: 20,
                    magister: 'BIOL8203',
                    id: '4jgnsh723y',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 3,
                    description:
                        'Toets op het gebied van reproductie en moleculaire biologie.',
                    domains: ['A', 'B1', 'E1', 'E2', 'E3'],
                    weight: 20,
                    magister: 'BIOL8204',
                    id: 'mte3o9np95',
                },
                {
                    type: 'PO',
                    year: 6,
                    period: 2,
                    description: 'Verslaglegging van praktijkonderdel(en)',
                    domains: ['A', 'E1', 'E2', 'F1', 'F2', 'F4'],
                    weight: 20,
                    id: 'drtwlr6mpg',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/biologie-vwo-2',
                    id: 'rnov6a8akw',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Natuur, Leven en Technologie',
            shortname: 'NLT',
            id: '1u6jxaj0m3',
            se_assignments: [
                {
                    type: 'PO',
                    year: 5,
                    period: 1,
                    description:
                        'Engelstalige presentatie in groepsverband over een door klimaatverandering veroorzaakt mondiaal probleem',
                    domains: ['A', 'B1', 'C2'],
                    weight: 15,
                    magister: 'NLT8201',
                    id: 'yt5n5xsuya',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 1,
                    description:
                        'Geschreven product(en) dat inzicht geeft op het gebied van seksualiteit en gedrag\nindividueel werk',
                    domains: ['A', 'D1', 'D2'],
                    weight: 17,
                    magister: 'NLT8202',
                    id: '7rd6f0gaah',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 2,
                    description:
                        'Geschreven product over metingen aan het melkwegstelsel\ngroepswerk',
                    domains: ['A', 'C1'],
                    weight: 17,
                    magister: 'NLT8203',
                    id: '95yy7a2zk',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 3,
                    description:
                        'Technisch ontwerp van een robot opstellen in groepsverband',
                    domains: ['A', 'B2', 'E1'],
                    weight: 17,
                    magister: 'NLT8204',
                    id: 'ttqdrd95q4',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 3,
                    description:
                        'Individuele opdracht naar aanleiding van een bezoek aan externe organisatie op het gebied van duurzaamheid',
                    domains: ['A', 'E2'],
                    weight: 17,
                    magister: 'NLT8205',
                    id: 'mfujt5tlpj',
                },
                {
                    type: 'PO',
                    year: 6,
                    period: 2,
                    description:
                        'Individueel uitwerken van enkele huiswerkopdrachten over fundamentele theorieën in een natuurwetenschap naar keuze',
                    domains: ['A', 'F1'],
                    weight: 17,
                    magister: 'NLT8302',
                    id: '8g0vfrexow',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Wiskunde B',
            shortname: 'WisB',
            id: 'jbw2r2cjlb',
            se_assignments: [
                {
                    type: 'SET',
                    year: 5,
                    period: 1,
                    description: 'Toets over goniometrische functies',
                    domains: ['D'],
                    weight: 15,
                    magister: 'WISB8201',
                    id: '3645gcx0n4',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 2,
                    description:
                        'Wiskunde in teams: Wiskunde B-dag\nDe leerlingen werken in groepjes van ca. 4 aan een wiskunde B dag opdracht. Onderwerpen zijn wisselend en spreken kennis en vaardigheden uit meerdere domeinen aan.',
                    domains: ['A1', 'A2', 'F'],
                    weight: 10,
                    magister: 'WISB8202',
                    id: '4sf3nykl59',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 4,
                    description: 'Toets over integreren en differentiëren',
                    domains: ['C'],
                    weight: 30,
                    magister: 'WISB8203',
                    id: '9w5jxlu4mi',
                },
                {
                    type: 'PO',
                    year: 6,
                    period: 2,
                    description:
                        'Keuzeonderwerp\nDe leerlingen werken individueel een keuze-onderwerp uit, bijvoorbeeld uit de zebraboekjes en geven daar een presentatie over.',
                    domains: ['A', 'F'],
                    weight: 10,
                    id: 'x3eylkvg6w',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 2,
                    description: 'Toets over alle meetkunde',
                    domains: ['E'],
                    weight: 35,
                    id: 'ykx7val347',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/biologie-vwo-2',
                    id: 'a301lmcwsp',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Wiskunde D',
            shortname: 'WisD',
            optional: true,
            id: 'zzhzstumsx',
            se_assignments: [
                {
                    type: 'SET',
                    year: 5,
                    period: 1,
                    description: 'Matrices en ruimterekenen',
                    domains: ['D3'],
                    weight: 10,
                    magister: 'WISD8201',
                    id: 'ttzm0zf9m7',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 2,
                    description: 'Toevalsvariabelen en kansverdeling',
                    domains: ['B3', 'B4'],
                    weight: 10,
                    magister: 'WISD8202',
                    id: 'gw7p763u55',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 3,
                    description: 'Meetkundige en andere bewijzen',
                    domains: ['D1'],
                    weight: 15,
                    magister: 'WISD8203',
                    id: 'mfqfmo2l85',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 4,
                    description: 'Complexe getallen',
                    domains: ['E'],
                    weight: 10,
                    magister: 'WISD8204',
                    id: 'e59b5uko1e',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 4,
                    description:
                        'Wetenschap in de praktijk - Besmettelijke ziekten',
                    domains: ['A', 'C', 'F', 'G'],
                    weight: 10,
                    magister: 'WISD8206',
                    id: 'g9g7w0cs1g',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 1,
                    description: 'Kegelsneden',
                    domains: ['D2'],
                    weight: 10,
                    id: '1ttniiwdqc',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 2,
                    description:
                        'Correlatie, regressie, verdelingen en hypothese toetsen',
                    domains: ['B5', 'B6', 'B7'],
                    weight: 15,
                    id: 'vl9vqadsoh',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 3,
                    description: 'Differentiaalvergelijkingen',
                    domains: ['C2', 'C3', 'F'],
                    weight: 10,
                    id: 'parew325rb',
                },
                {
                    type: 'PO',
                    year: 6,
                    period: 3,
                    description:
                        'Onderzoeksproject\nEen geschreven verslag met een mondelinge presentatie aan de klas',
                    domains: ['A', 'G'],
                    weight: 10,
                    id: 'p0ovmrxnc0',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Filosofie',
            shortname: 'Fi.',
            optional: true,
            id: '9i65zn7fb7',
            se_assignments: [
                {
                    type: 'SET',
                    year: 5,
                    period: 1,
                    description:
                        'Individuele toets over |\n- Ethiek: Utilisme, Deontologie, Deugdethiek, Slavenmoraal\n- Antropologie: klassieke, moderne en postmoderne mensbeeld.',
                    domains: ['B', 'C'],
                    weight: 25,
                    magister: 'FI8201',
                    id: 'piqyaduiep',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 2,
                    description:
                        'Wetenschapsfilosofie\n- Reductionisme\n- Correspondentietheorie\n- Kritisch rationalisme\n- Coherentietheorie\n- Conventietheorie\n- Pragmatisme',
                    domains: ['E'],
                    weight: 25,
                    magister: 'FI8202',
                    id: 'blj4nhc7cr',
                },
                {
                    type: 'SET',
                    year: 5,
                    period: 3,
                    description:
                        'Individuele toets over Kennisleer:\n- Platonisme\n- Taoïsme\n- Empirisme,\n- Rationalisme,\n- Transcendentalisme,\n- Perspectivisme\n- Pragmatisme\n- Deconstructivisme',
                    domains: ['D'],
                    weight: 25,
                    magister: 'FI8203',
                    id: '7d9ld91une',
                },
                {
                    type: 'PO',
                    year: 5,
                    period: 4,
                    description:
                        'Groepsopdracht (2 a 3) waarin de leerlingen een les verzorgen over:\npolitieke en sociale filosofie:\n- Theorie uitleggen, politiek/sociaal fenomeen analyseren, discussie over stelling begeleiden.',
                    domains: ['A'],
                    weight: 25,
                    magister: 'FI8204',
                    id: 'o7gjalrjtv',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/filosofie-vwo',
                    id: '66xgn2c76r',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Nederlands',
            shortname: 'Ned.',
            id: 'zx30rjiwo1',
            se_assignments: [
                {
                    type: 'SET',
                    year: 5,
                    period: 3,
                    description:
                        'Gedocumenteerd schrijven: beschouwing schrijven op basis van bronnen',
                    domains: ['A', 'A1', 'A2', 'A3', 'C', 'D'],
                    weight: 30,
                    magister: 'NETL8206',
                    id: 'fb0ed940hj',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 1,
                    description: 'Motivatiebrief schrijven',
                    domains: ['C', 'D'],
                    weight: 25,
                    id: 'npd3gqz79f',
                },
                {
                    type: 'MET',
                    year: 6,
                    period: 2,
                    description:
                        'Literatuur - Voordracht en mondeling over vier romans van de literatuurlijst\n\nVoordracht en mondeling worden gemiddeld en leveren één cijfer op\n\nIndeling door docent. Herkansing gebeurt in bijbehorende periode.',
                    domains: ['B', 'D', 'E', 'E1', 'E2', 'E3'],
                    weight: 45,
                    magister: 'NETL8207',
                    id: '9aicnqjbgs',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/nederlands-vwo-2',
                    id: 'sdptpz6nsb',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Engels',
            shortname: 'Eng.',
            id: 'ns17jgif2b',
            se_assignments: [
                {
                    type: 'MET',
                    year: 6,
                    period: 1,
                    description: 'Dragon’s Den pitch met aansluitend gesprek.',
                    domains: ['C', 'C1', 'C2'],
                    weight: 35,
                    magister: 'ENTL8301',
                    id: 'tzma7h6lza',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 2,
                    description: 'Essay over sociaal/economisch thema',
                    domains: ['D'],
                    weight: 35,
                    magister: 'ENTL8302',
                    id: 'ua1f2n494n',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 3,
                    description: 'Luistertoets Engels Cito',
                    domains: ['B'],
                    weight: 30,
                    magister: 'ENTL8303',
                    id: 'e484pmwj16',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/engels-vwo-2',
                    id: 'nuryatwprl',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Engels (Versneld)',
            shortname: 'SnelEng.',
            replaces: 'ns17jgif2b',
            id: 'vrzx1r9o5w',
            se_assignments: [
                {
                    type: 'MET',
                    year: 5,
                    period: 1,
                    description:
                        'Presentatie met aansluitend gesprek over een onderwerp passend bij het gekozen profiel.',
                    domains: ['C', 'C1', 'C2'],
                    weight: 35,
                    magister: 'ENTL8301',
                    id: 'knigogvo82',
                },
                {
                    like: 'ua1f2n494n',
                    year: 5,
                    period: 2,
                    id: '8rly123ah6',
                },
                {
                    like: 'e484pmwj16',
                    year: 5,
                    period: 3,
                    id: 'rpl6l1jjox',
                },
            ],
            ce_assignments: [
                {
                    like: 'nuryatwprl',
                    id: 'lrse06770r',
                },
            ],
        },
        {
            type: 'VAK',
            fullname: 'Spaans',
            shortname: 'Sp.',
            id: 'ahpadn77oh',
            se_assignments: [
                {
                    type: 'SET',
                    year: 6,
                    period: 1,
                    description:
                        'Schrijfvaardigheid:\nProfielrelevante schrijfopdracht in vier delen (B1)\nSchriftelijke opdrachten in vier delen: reactie - informatie vragen en verstrekken - presentatie - literair verslag.\nDoor docent goedgekeurde hulpmiddelen toegestaan.',
                    domains: ['D', 'D1', 'D2', 'E', 'E1', 'E2', 'E3'],
                    weight: 35,
                    id: 'c7qbfcy1gn',
                },
                {
                    type: 'MET',
                    year: 6,
                    period: 2,
                    description:
                        'Spreekvaardigheid:\nSpaanstalige cultuur en literatuur (B1+)\nMonoloog (presentatie in groepjes) en interactie (spontaan reageren op vragen uit het publiek). Door docent goedgekeurde hulpmiddelen toegestaan.',
                    domains: ['C', 'C1', 'C2', 'E', 'E1', 'E2', 'E3'],
                    weight: 35,
                    id: 'd2jadrap3j',
                },
                {
                    type: 'SET',
                    year: 6,
                    period: 3,
                    description: 'Cito Kijk- en luistertoets Spaans (B2)',
                    domains: ['B'],
                    weight: 30,
                    id: '5dwmzbevfi',
                },
            ],
            ce_assignments: [
                {
                    type: 'CSE',
                    link: 'https://www.examenblad.nl/examen/spaans-vwo-2',
                    id: 'uwqracxa6m',
                },
            ],
        },
        {
            type: 'COMB',
            fullname: 'Combinatiecijfer',
            shortname: 'Comb.',
            id: 'xwfhtiidpd',
            assignments: [
                {
                    type: 'VAK',
                    fullname: 'Maatschappijleer',
                    shortname: 'Maat.',
                    id: '50t1897ct8',
                    se_assignments: [
                        {
                            type: 'PO',
                            year: 4,
                            period: 1,
                            description:
                                'Politieke partijen en opvattingen over de verzorgingsstaat boekje in groepjes',
                            domains: ['A', 'C', 'D'],
                            weight: 25,
                            magister: 'MAAT8111',
                            id: 'hfhyyrjk40',
                        },
                        {
                            type: 'PO',
                            year: 4,
                            period: 2,
                            description:
                                'Rechten, rechtvaardigheid en de pluriforme samenleving documentaire in groepjes',
                            domains: ['A', 'B', 'C', 'E'],
                            weight: 25,
                            magister: 'MAAT8112',
                            id: 'w3tfmzaq0o',
                        },
                        {
                            type: 'SET',
                            year: 5,
                            period: 1,
                            description: 'Politiek: regels en instituties',
                            domains: ['B', 'C', 'D'],
                            weight: 25,
                            magister: 'MAAT8201',
                            id: 'ywoflqkdxz',
                        },
                        {
                            type: 'PO',
                            year: 5,
                            period: 2,
                            description:
                                'Portfolio: maatschappelijke instituties en ontwikkelingen',
                            domains: ['A', 'B', 'C', 'D', 'E'],
                            weight: 25,
                            magister: 'MAAT8202',
                            id: '8ulmc1jqp7',
                        },
                    ],
                },
                {
                    type: 'VAK',
                    fullname:
                        'Algemene Natuurwetenschappen (Filosofie en Technologie)',
                    shortname: 'ANW',
                    id: 't6we4xy0a3',
                    se_assignments: [
                        {
                            type: 'PO',
                            year: 5,
                            period: 1,
                            description:
                                "Duurzaamheid\nDuo's\n- Technisch ontwerp (ontwerpcyclus)\n- Product of prototype\n- Reflectie op duurzaamheidsfilosofie",
                            domains: ['A2', 'A4', 'A5', 'D2'],
                            weight: 20,
                            magister: 'ANW8201',
                            id: 'ejsxrxx47q',
                        },
                        {
                            type: 'SET',
                            year: 5,
                            period: 2,
                            description:
                                'Wetenschapsfilosofie\n- Reductionisme\n- Correspondentietheorie\n- Kritisch rationalisme\n- Coherentietheorie\n- Coventionalisme\n- Pragmatisme',
                            domains: ['B1', 'B2', 'C3', 'F3'],
                            weight: 20,
                            magister: 'ANW8202',
                            id: 'davve54u4w',
                        },
                        {
                            type: 'PO',
                            year: 5,
                            period: 3,
                            description:
                                "Modelleren\nDuo's\n\nProgrammeren en toelichten van een model in Netlogo",
                            domains: ['A6', 'B1', 'B2', 'C3', 'F3'],
                            weight: 20,
                            magister: 'ANW8203',
                            id: '07joobkhw9',
                        },
                        {
                            type: 'PO',
                            year: 5,
                            period: 4,
                            description:
                                'Onderzoekscyclus voor PWS\nDuo of individueel\nData Science toegepast in profielwerkstuk',
                            domains: ['A1', 'A3'],
                            weight: 20,
                            magister: 'ANW8204',
                            id: 'xsvzaplzbl',
                        },
                        {
                            type: 'MET',
                            year: 6,
                            period: 1,
                            description:
                                'Cultuurkritiek\nDebat (2 tegen 2) over de invloed van technologie op het individu en de maatschappij\nIndividuele beoordeling',
                            domains: ['A7', 'B3'],
                            weight: 20,
                            id: '7qgusse1xa',
                        },
                    ],
                },
                {
                    type: 'VAK',
                    fullname: 'Culturele en Kunstzinnige vorming',
                    shortname: 'CKV',
                    id: '27ox1mmvn2',
                    se_assignments: [
                        {
                            type: 'PO',
                            year: 4,
                            period: 1,
                            description:
                                'Corporate identity boek politieke partijen op basis van politieke ideologie en geschiedenis in groepjes',
                            domains: ['A', 'B', 'C', 'D'],
                            weight: 33,
                            magister: 'CKV8111',
                            id: 'qvkw1mzs5y',
                        },
                        {
                            type: 'PO',
                            year: 4,
                            period: 2,
                            description:
                                'Documentaire maken over maatschappelijk onderwerp in groepjes',
                            domains: ['A', 'B', 'C', 'D'],
                            weight: 33,
                            magister: 'CKV8112',
                            id: 'zswpp19h9x',
                        },
                        {
                            type: 'PO',
                            year: 5,
                            period: 2,
                            description:
                                'Portfolio CKV-activiteiten: keuze, bijwonen, beschrijving en analyse van 4 verschillende culturele activiteiten. Presentatie in een portfolio. (individueel)',
                            domains: ['A', 'B', 'C', 'D'],
                            weight: 34,
                            magister: 'CKV8201',
                            id: 'wo4mih1hcq',
                        },
                    ],
                },
                {
                    type: 'PO',
                    year: 6,
                    period: 3,
                    description:
                        'Verslaglegging van het profielwerkstuk en bijbehorende mondelinge toelichting',
                    id: 'vnhbeley4l',
                },
            ],
        },
    ],
};
